@startuml overview
autoactivate on
hide footbox

actor "User" as USER

box "AWS" #LightGoldenRodYellow
participant "API\nGateway"           as APIGW
participant "Lambda\nFunction"       as LAMBDA
participant "Parameter\nStore"       as PARM
participant "SimpleEmail\nService (SES)"  as SES
participant "DynamoDB"               as DYNAMODB

' AWS
USER   ->  APIGW  : Submit contact form
APIGW  ->  LAMBDA : Relay submitted form

== Validate hCaptcha ==
LAMBDA ->  PARM   : Get captcha secret and sitekey
return
end box

' hCaptcha
box "hCaptcha" #LightSkyBlue
participant "hCaptcha" as CAPTCHA
LAMBDA ->  CAPTCHA : Validate token
return
end box

== Send email (optional) ==

' AWS
LAMBDA ->  SES : Send email
return

== Log to DynamoDB (optional) ==

LAMBDA ->  DYNAMODB : Write to table
return

== Send Discord message (optional) ==
box "Discord" #Plum
participant "Discord" as DISCORD
LAMBDA ->  DISCORD : Send message to Discord channel
return

== Send Slack message (optional) ==
box "Slack" #LimeGreen
participant "Slack" as SLACK
LAMBDA ->  SLACK : Send message to Slack channel
return

APIGW  <-- LAMBDA : Return response
return Relay response

@enduml
